# General
title: "KodeBlog V2.0"
email: "codemaster.eddie@gmail.com"
description: "yet another personal blog :)"
baseurl: ""
url: "0xedd1e.github.io"
github_username: "0xedd1e"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard-wrap: false
highlighter: rouge
encoding: utf-8

# Sass
sass:
  style: compressed
  sass_dir: _sass
